name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: microsoft
          java-version: 17
          cache: gradle

      - name: Build
        run: |
          chmod +x ./gradlew
          ./gradlew build --no-daemon --warning-mode all
