name: Build

on:
  pull_requst:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: microsoft
          java-version: 17
          cache: gradle

      - name: Build
        run: ./gradlew build --no-daemon
